services:
  backend:
    build:
      context: ./backend
    networks:
      - default
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    container_name: backend
