services:
  backend:
    image: google-calendar-backend
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
      secrets:
        - credentials
    networks:
      - default
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py

secrets:
  credentials:
    file: ./backend/creds/credentials.json

volumes:
  creds:
