services:
  backend:
    image: google-calendar-backend
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
      secrets:
        - credentials
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
    volumes:
      - ./backend/creds:/app/creds

  frontend:
    image: google-calendar-frontend
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - VITE_BACKEND_URL=http://localhost:8080/api
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend

secrets:
  credentials:
    file: ./backend/creds/credentials.json

volumes:
  creds:
