services:
  backend:
    build:
      context: ./backend
      secrets:
        - credentials
    networks:
      - default
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    container_name: backend

secrets:
  credentials:
    file: ./backend/src/creds/credentials.json
