name: google-calendar-api
channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - flask
  - flask-restful
  - flask-cors
  - google-api-python-client
  - google-auth
  - google-auth-oauthlib
  - invoke
  - ruff
  - pytest
  - InquirerPy
  - typeguard
  - gunicorn
  - waitress
  - parsedatetime
  - babel
  - python-dateutil
