name: google-calendar-year
channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - flask
  - flask-restful
  - flask-cors
  - google-api-python-client
  - google-auth
  - google-auth-oauthlib
  - invoke
  - autoflake
  - isort
  - flake8
  - pytest
