name: Codespell

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

permissions:
  contents: read

jobs:
  codespell:
    name: Check for spelling errors
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Codespell
        uses: codespell-project/actions-codespell@v2
        with:
          # https://github.com/codespell-project/actions-codespell/tree/v2.1?tab=readme-ov-file#parameter-only_warn
          only_warn: 1
          skip: package-lock.json
